=== vcedeno/pipelineCode/experiment-pipeline/test/results/h1/output/schemas/phase.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Phases",
    "description": "Phases in an experiment",
    "type": "array",
    "items" : {
    "type": "object",
    "properties": {
        "phaseid": {
            "description": "The unique identifier for a phase",
            "type": "string"
        },
        "phasedescriptionid": {
            "description": "The phase description id",
            "type": "string"
        },
        "experimentid": {
            "description": "Phase experiment id",
            "type": "integer"
        },
        "phaseorder": {
            "description": "Order of phase in experiment",
            "type": "integer"
        },
        "begin": {
            "description": "Start time of a phase in experiment",
            "type": "number"
        },
        "duration": {
            "description": "Duration of a phase in seconds",
            "type": "integer"
        },
        "d": {
            "description": "Connections between players",
            "type": "integer"
        },
        "n": {
            "description": "Number of players",
            "type": "integer"
        }
    },
    "required": ["phaseid","phasedescriptionid","experimentid","phaseorder","begin","duration"]
    }
}

=== vcedeno/pipelineCode/data-analytics-pipeline/json-schema/inputTransformation/datasets/phase.json
[
  {
    "phaseid": "5ydhsfg61",
    "phasedescriptionid": "anagrams",
    "experimentid": 1,
    "phaseorder": 1,
    "begin": 1500666678.0,
    "duration": 330,
    "d": 2,
    "n": 10
  },
  {
    "phaseid": "5ydhsfg62",
    "phasedescriptionid": "publicgoods",
    "experimentid": 1,
    "phaseorder": 2,
    "begin": 1500667306.0,
    "duration": 23,
    "d": 0,
    "n": 10
  },
  {
    "phaseid": "gbwspag31",
    "phasedescriptionid": "anagrams",
    "experimentid": 2,
    "phaseorder": 1,
    "begin": 1501084376.0,
    "duration": 308,
    "d": 2,
    "n": 10
  },
  {
    "phaseid": "gbwspag32",
    "phasedescriptionid": "publicgoods",
    "experimentid": 2,
    "phaseorder": 2,
    "begin": 1501085103.0,
    "duration": 4972,
    "d": 0,
    "n": 10
  },
  {
    "phaseid": "89ykytnu1",
    "phasedescriptionid": "anagrams",
    "experimentid": 3,
    "phaseorder": 1,
    "begin": 1501188119.0,
    "duration": 309,
    "d": 2,
    "n": 10
  },
  {
    "phaseid": "89ykytnu2",
    "phasedescriptionid": "publicgoods",
    "experimentid": 3,
    "phaseorder": 2,
    "begin": 1501188729.0,
    "duration": 50,
    "d": 0,
    "n": 10
  },
  {
    "phaseid": "ef0hzbwg1",
    "phasedescriptionid": "anagrams",
    "experimentid": 4,
    "phaseorder": 1,
    "begin": 1501251511.0,
    "duration": 312,
    "d": 2,
    "n": 10
  },
  {
    "phaseid": "ef0hzbwg2",
    "phasedescriptionid": "publicgoods",
    "experimentid": 4,
    "phaseorder": 2,
    "begin": 1501252211.0,
    "duration": 26,
    "d": 0,
    "n": 10
  },
  {
    "phaseid": "jrseoprn1",
    "phasedescriptionid": "anagrams",
    "experimentid": 5,
    "phaseorder": 1,
    "begin": 1502200606.0,
    "duration": 327,
    "d": 2,
    "n": 10
  },
  {
    "phaseid": "jrseoprn2",
    "phasedescriptionid": "publicgoods",
    "experimentid": 5,
    "phaseorder": 2,
    "begin": 1502201250.0,
    "duration": 31,
    "d": 0,
    "n": 10
  },
  {
    "phaseid": "7tbi6mwd1",
    "phasedescriptionid": "anagrams",
    "experimentid": 6,
    "phaseorder": 1,
    "begin": 1502215071.0,
    "duration": 306,
    "d": 2,
    "n": 10
  },
  {
    "phaseid": "7tbi6mwd2",
    "phasedescriptionid": "publicgoods",
    "experimentid": 6,
    "phaseorder": 2,
    "begin": 1502215580.0,
    "duration": 37,
    "d": 0,
    "n": 10
  },
  {
    "phaseid": "pzv22f481",
    "phasedescriptionid": "anagrams",
    "experimentid": 7,
    "phaseorder": 1,
    "begin": 1502896286.0,
    "duration": 307,
    "d": 2,
    "n": 10
  },
  {
    "phaseid": "pzv22f482",
    "phasedescriptionid": "publicgoods",
    "experimentid": 7,
    "phaseorder": 2,
    "begin": 1502896921.0,
    "duration": 43,
    "d": 0,
    "n": 10
  },
  {
    "phaseid": "frec209s1",
    "phasedescriptionid": "anagrams",
    "experimentid": 8,
    "phaseorder": 1,
    "begin": 1502903151.0,
    "duration": 306,
    "d": 2,
    "n": 10
  },
  {
    "phaseid": "frec209s2",
    "phasedescriptionid": "publicgoods",
    "experimentid": 8,
    "phaseorder": 2,
    "begin": 1502903752.0,
    "duration": 56,
    "d": 0,
    "n": 10
  },
  {
    "phaseid": "wzq3kfp91",
    "phasedescriptionid": "anagrams",
    "experimentid": 9,
    "phaseorder": 1,
    "begin": 1502905088.0,
    "duration": 317,
    "d": 2,
    "n": 10
  },
  {
    "phaseid": "wzq3kfp92",
    "phasedescriptionid": "publicgoods",
    "experimentid": 9,
    "phaseorder": 2,
    "begin": 1502905873.0,
    "duration": 23,
    "d": 0,
    "n": 10
  },
  {
    "phaseid": "aab8cga31",
    "phasedescriptionid": "anagrams",
    "experimentid": 10,
    "phaseorder": 1,
    "begin": 1502909512.0,
    "duration": 307,
    "d": 2,
    "n": 10
  },
  {
    "phaseid": "aab8cga32",
    "phasedescriptionid": "publicgoods",
    "experimentid": 10,
    "phaseorder": 2,
    "begin": 1502910133.0,
    "duration": 23,
    "d": 0,
    "n": 10
  },
  {
    "phaseid": "kfn4hfj71",
    "phasedescriptionid": "anagrams",
    "experimentid": 11,
    "phaseorder": 1,
    "begin": 1503594687.0,
    "duration": 312,
    "d": 2,
    "n": 5
  },
  {
    "phaseid": "kfn4hfj72",
    "phasedescriptionid": "publicgoods",
    "experimentid": 11,
    "phaseorder": 2,
    "begin": 1503595372.0,
    "duration": 33,
    "d": 0,
    "n": 5
  },
  {
    "phaseid": "r7gyn3n41",
    "phasedescriptionid": "anagrams",
    "experimentid": 12,
    "phaseorder": 1,
    "begin": 1503598159.0,
    "duration": 307,
    "d": 2,
    "n": 5
  },
  {
    "phaseid": "r7gyn3n42",
    "phasedescriptionid": "publicgoods",
    "experimentid": 12,
    "phaseorder": 2,
    "begin": 1503598842.0,
    "duration": 34,
    "d": 0,
    "n": 5
  },
  {
    "phaseid": "vjdla1q91",
    "phasedescriptionid": "anagrams",
    "experimentid": 13,
    "phaseorder": 1,
    "begin": 1503685679.0,
    "duration": 307,
    "d": 2,
    "n": 5
  },
  {
    "phaseid": "vjdla1q92",
    "phasedescriptionid": "publicgoods",
    "experimentid": 13,
    "phaseorder": 2,
    "begin": 1503686384.0,
    "duration": 50,
    "d": 0,
    "n": 5
  },
  {
    "phaseid": "ehcc5wgj1",
    "phasedescriptionid": "anagrams",
    "experimentid": 14,
    "phaseorder": 1,
    "begin": 1504107364.0,
    "duration": 305,
    "d": 2,
    "n": 5
  },
  {
    "phaseid": "ehcc5wgj2",
    "phasedescriptionid": "publicgoods",
    "experimentid": 14,
    "phaseorder": 2,
    "begin": 1504107891.0,
    "duration": 29,
    "d": 0,
    "n": 5
  },
  {
    "phaseid": "ub8pim6i1",
    "phasedescriptionid": "anagrams",
    "experimentid": 15,
    "phaseorder": 1,
    "begin": 1504189212.0,
    "duration": 306,
    "d": 2,
    "n": 5
  },
  {
    "phaseid": "ub8pim6i2",
    "phasedescriptionid": "publicgoods",
    "experimentid": 15,
    "phaseorder": 2,
    "begin": 1504189783.0,
    "duration": 28,
    "d": 0,
    "n": 5
  },
  {
    "phaseid": "942arxyx1",
    "phasedescriptionid": "anagrams",
    "experimentid": 16,
    "phaseorder": 1,
    "begin": 1504189474.0,
    "duration": 309,
    "d": 2,
    "n": 5
  },
  {
    "phaseid": "942arxyx2",
    "phasedescriptionid": "publicgoods",
    "experimentid": 16,
    "phaseorder": 2,
    "begin": 1504189973.0,
    "duration": 11,
    "d": 0,
    "n": 5
  },
  {
    "phaseid": "emwpven21",
    "phasedescriptionid": "anagrams",
    "experimentid": 17,
    "phaseorder": 1,
    "begin": 1504192958.0,
    "duration": 315,
    "d": 2,
    "n": 5
  },
  {
    "phaseid": "emwpven22",
    "phasedescriptionid": "publicgoods",
    "experimentid": 17,
    "phaseorder": 2,
    "begin": 1504193652.0,
    "duration": 39,
    "d": 0,
    "n": 5
  },
  {
    "phaseid": "oi2esved1",
    "phasedescriptionid": "anagrams",
    "experimentid": 18,
    "phaseorder": 1,
    "begin": 1504214296.0,
    "duration": 307,
    "d": 2,
    "n": 5
  },
  {
    "phaseid": "oi2esved2",
    "phasedescriptionid": "publicgoods",
    "experimentid": 18,
    "phaseorder": 2,
    "begin": 1504214985.0,
    "duration": 38,
    "d": 0,
    "n": 5
  },
  {
    "phaseid": "2m9rd2cp1",
    "phasedescriptionid": "anagrams",
    "experimentid": 19,
    "phaseorder": 1,
    "begin": 1504803799.0,
    "duration": 327,
    "d": 2,
    "n": 20
  },
  {
    "phaseid": "2m9rd2cp2",
    "phasedescriptionid": "publicgoods",
    "experimentid": 19,
    "phaseorder": 2,
    "begin": 1504804563.0,
    "duration": 44,
    "d": 0,
    "n": 20
  },
  {
    "phaseid": "31f1vzlc1",
    "phasedescriptionid": "anagrams",
    "experimentid": 20,
    "phaseorder": 1,
    "begin": 1504881164.0,
    "duration": 310,
    "d": 2,
    "n": 20
  },
  {
    "phaseid": "31f1vzlc2",
    "phasedescriptionid": "publicgoods",
    "experimentid": 20,
    "phaseorder": 2,
    "begin": 1504881829.0,
    "duration": 53,
    "d": 0,
    "n": 20
  },
  {
    "phaseid": "ya61mn6p1",
    "phasedescriptionid": "anagrams",
    "experimentid": 21,
    "phaseorder": 1,
    "begin": 1504889091.0,
    "duration": 307,
    "d": 2,
    "n": 20
  },
  {
    "phaseid": "ya61mn6p2",
    "phasedescriptionid": "publicgoods",
    "experimentid": 21,
    "phaseorder": 2,
    "begin": 1504889678.0,
    "duration": 33,
    "d": 0,
    "n": 20
  },
  {
    "phaseid": "bquung7a1",
    "phasedescriptionid": "anagrams",
    "experimentid": 22,
    "phaseorder": 1,
    "begin": 1505155916.0,
    "duration": 210,
    "d": 2,
    "n": 20
  },
  {
    "phaseid": "bquung7a2",
    "phasedescriptionid": "publicgoods",
    "experimentid": 22,
    "phaseorder": 2,
    "begin": 1505156531.0,
    "duration": 50,
    "d": 0,
    "n": 20
  },
  {
    "phaseid": "i0wkxelq1",
    "phasedescriptionid": "anagrams",
    "experimentid": 23,
    "phaseorder": 1,
    "begin": 1505237279.0,
    "duration": 312,
    "d": 2,
    "n": 20
  },
  {
    "phaseid": "i0wkxelq2",
    "phasedescriptionid": "publicgoods",
    "experimentid": 23,
    "phaseorder": 2,
    "begin": 1505237939.0,
    "duration": 33,
    "d": 0,
    "n": 20
  },
  {
    "phaseid": "eu7tcyrg1",
    "phasedescriptionid": "anagrams",
    "experimentid": 24,
    "phaseorder": 1,
    "begin": 1505841827.0,
    "duration": 323,
    "d": 2,
    "n": 20
  },
  {
    "phaseid": "eu7tcyrg2",
    "phasedescriptionid": "publicgoods",
    "experimentid": 24,
    "phaseorder": 2,
    "begin": 1505842589.0,
    "duration": 51,
    "d": 0,
    "n": 20
  },
  {
    "phaseid": "krab6ohp1",
    "phasedescriptionid": "anagrams",
    "experimentid": 25,
    "phaseorder": 1,
    "begin": 1506457072.0,
    "duration": 324,
    "d": 2,
    "n": 20
  },
  {
    "phaseid": "krab6ohp2",
    "phasedescriptionid": "publicgoods",
    "experimentid": 25,
    "phaseorder": 2,
    "begin": 1506457796.0,
    "duration": 32,
    "d": 0,
    "n": 20
  },
  {
    "phaseid": "s14j5qtb1",
    "phasedescriptionid": "anagrams",
    "experimentid": 26,
    "phaseorder": 1,
    "begin": 1506965342.0,
    "duration": 322,
    "d": 2,
    "n": 20
  },
  {
    "phaseid": "s14j5qtb2",
    "phasedescriptionid": "publicgoods",
    "experimentid": 26,
    "phaseorder": 2,
    "begin": 1506966195.0,
    "duration": 72,
    "d": 0,
