=== vcedeno/pipelineCode/experiment-pipeline/test/results/h1/output/schemas/phasedesc.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Phases",
    "description": "Phases in an experiment",
    "type": "array",
    "items" : {
    "type": "object",
    "properties": {
        "phaseid": {
            "description": "The unique identifier for a phase",
            "type": "string"
        },
        "beginparameters" : {
          "type" : "array",
           "items" : {
               "type" : "object",
               "properties" : {
        	   		"parameter": {
            		"description": "Beginning parameters in phase",
            		"type": "string"
        			}
       			}
       		}
       	 },
       	"endparameters" : {
          "type" : "array",
           "items" : {
               "type" : "object",
               "properties" : {
        	   		"parameter": {
            		"description": "End parameters in phase",
            		"type": "string"
        			}
       			}
       		}
       	 },
       	"actions" : {
          "type" : "array",
           "items" : {
               "type" : "object",
               "properties" : {
        	   		"action": {
            		"description": "Actions in phase",
            		"type": "string"
        			}
       			}
       		}
       	 },
       	 "synchronousactions" : {
          "type" : "array",
           "items" : {
               "type" : "object",
               "properties" : {
        	   		"actionrequest": {
            		"description": "Action request id",
            		"type": "string"
        			},
        			"actionreply": {
            		"description": "Action reply id",
            		"type": "string"
        			}
       			}
       		}
       	 },
       	"features" : {
          "type" : "array",
           "items" : {
               "type" : "object",
               "properties" : {
        	   		"feature": {
            		"description": "feature vector for models",
            		"type": "string"
        			}
       			}
       		}
       	 }
    },
    "required": ["phaseid"]
    }
}

=== vcedeno/pipelineCode/experiment-pipeline/test/results/h1/output/datasets/phasedesc.json
[
  {
    "phaseid": "anagrams",
    "beginparameters": [
      {
        "parameter": "letter1"
      },
      {
        "parameter": "letter2"
      },
      {
        "parameter": "letter3"
      },
      {
        "parameter": "difi1distanceScale"
      },
      {
        "parameter": "difi1overlapScale"
      }
    ],
    "endparameters": [
      {
        "parameter": "numWords"
      },
      {
        "parameter": "scrabblescore"
      }
    ],
    "actions": [
      {
        "action": "word"
      },
      {
        "action": "requestsent"
      },
      {
        "action": "replysent"
      }
    ],
    "synchronousactions": [
      {
        "actionrequest": "requestsent",
        "actionreply": "replysent"
      }
    ],
    "features": [
      {
        "feature": "XE"
      },
      {
        "feature": "XB"
      },
      {
        "feature": "XL"
      },
      {
        "feature": "XW"
      },
      {
        "feature": "XC"
      },
      {
        "feature": "xReqS"
      },
      {
        "feature": "xRpyR"
      },
      {
        "feature": "xReqR"
      },
      {
        "feature": "xRpyS"
      }
    ]
  },
  {
    "phaseid": "publicgoods",
    "beginparameters": [
      {
        "parameter": "difi2distanceScale"
      },
      {
        "parameter": "difi2overlapScale"
      }
    ],
    "endparameters": [
      {
        "parameter": "contribution"
      },
      {
        "parameter": "profit"
      },
      {
        "parameter": "difi3distanceScale"
      },
      {
        "parameter": "difi3overlapScale"
      }
    ],
    "actions": [
      {
        "action": ""
      }
    ],
    "synchronousactions": [
      {
        "actionrequest": "",
        "actionreply": ""
      }
    ],
    "features": [
      {
        "feature": ""
      }
    ]
  }
]
