=== vcedeno/pipelineCode/jsonInputPipeline/schemas/data-analytics-pipeline.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "ngs2-data-analytics-1-1#",
    "type": "object",
    "definitions": {
        "VolumeServiceFileReference": {
            "id": "VolumeServiceFileReference#",
            "description": "Reference to a VolumeService File",
            "definitions": {
                "VolumeServiceFileURL": {
                    "description": "URL pointing at Volume Service File",
                    "type": "string",
                    "format": "uri"
                },
                "VolumeServiceFileID": {
                    "description": "UUID of a vs file.  When an ID is used instead of a URL, services will assume their default configured VS as the container for this item",
                    "type": "string",
                    "format": "uuid"
                }
            },
            "oneOf": [
                {
                    "type": "string"
                },
                {
                    "type": "string"
                }
            ]
        }
    },
    "properties": {
        "experiment": {
            "type": "string",
            "description": "Experiments description file"
        },
        "phasedesc": {
            "type": "string",
            "description": "Phases description file"
        },
        "phase": {
            "type": "string",
            "description": "Phases registration file"
        },
        "action": {
            "type": "string",
            "description": "Actions registration file"
        },
        "player": {
            "type": "string",
            "description": "Players parameters registration file"
        },
        "functions": {
            "type": "array",
            "description": "Functions to be run for this pipeline",
            "minItems": 1,
            "items": {
                "type": "object",
                "properties": {
                    "function": {
                        "description": "Pipeline functions to execute",
                        "type": "string",
                        "enum": [
                            "h1",
                            "h2",
                            "h3",
                            "h4",
                            "h5",
                            "h6",
                            "h7",
                            "h8",
                            "h9",
                            "h10",
                            "h11",
                            "h12",
                            "h13",
                            "h14"                         
                        ]
                    },
                    "actionId": {
                        "type": "string",
                        "description": "Required for h2, h3, h4, h5, h6"
                    },
                    "windowSize": {
                        "type": "integer",
                        "description": "Required for h3, h4, h7"
                    }
                    ,
                    "bin": {
                        "type": "integer",
                        "description": "Required for h5, h6"
                    }
                },
                "required": [
                    "function"
                ]
            }
        }
    },
    "required": [
        "experiment",
        "phasedesc",
        "phase",
        "player",
        "functions"
    ]
}

=== vcedeno/pipelineCode/jsonInputPipeline/input/data-analytics-pipeline copy.json
{
        "experiment": "/data-analytics-pipeline/json-schema/inputTransformation/datasets/experiment.json",
        "phasedesc": "/data-analytics-pipeline/json-schema/inputTransformation/datasets/phasedesc.json",
        "phase": "/data-analytics-pipeline/json-schema/inputTransformation/datasets/phase.json",
        "action": "/data-analytics-pipeline/json-schema/inputTransformation/datasets/action.json",
        "player": "/data-analytics-pipeline/json-schema/inputTransformation/datasets/player.json",
        "functions": 
        [
      		{
       			"function": "h9",
        		"windowSize": 10,
        		"nd":"n10d2,n20d2,n15d4,n15d2,n15d3,n15d5,n15d6,n15d8",
        		"cat1numletters":3,
        		"cat1time":15,
        		"cat2numwords":3,
        		"cat2time":30,
        		"numseconds":300
      		}
    	]
}

=== vcedeno/pipelineCode/jsonInputPipeline/input/data-analytics-pipelineh7.json
{
        "experiment": "/data-analytics-pipeline/json-schema/inputTransformation/datasets/experiment.json",
        "phasedesc": "/data-analytics-pipeline/json-schema/inputTransformation/datasets/phasedesc.json",
        "phase": "/data-analytics-pipeline/json-schema/inputTransformation/datasets/phase.json",
        "action": "/data-analytics-pipeline/json-schema/inputTransformation/datasets/action.json",
        "player": "/data-analytics-pipeline/json-schema/inputTransformation/datasets/player.json",
        "functions": 
        [
      		{
       			"function": "h7",
       			"featureId": "all",
        		"windowSize": 1,
        		"nd":"n10d2,n15d2,n15d3,n15d4,n15d5,n15d6,n15d8,n20d2",
        		"numseconds":300
      		}
    	]
}

=== vcedeno/pipelineCode/jsonInputPipeline/input/data-analytics-pipelineh5.json
{
        "experiment": "/data-analytics-pipeline/json-schema/inputTransformation/datasets/experiment.json",
        "phasedesc": "/data-analytics-pipeline/json-schema/inputTransformation/datasets/phasedesc.json",
        "phase": "/data-analytics-pipeline/json-schema/inputTransformation/datasets/phase.json",
        "action": "/data-analytics-pipeline/json-schema/inputTransformation/datasets/action.json",
        "player": "/data-analytics-pipeline/json-schema/inputTransformation/datasets/player.json",
        "functions": 
        [
      		{
       			"function": "h5",
       			"actionId":"requestsent",
        		"bin": 30,
        		"nd": "n15d6",
        		"numseconds":300
      		}
    	]
}
